const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const code=fs.readFileSync('src/Code.js','utf8'),html=fs.readFileSync('src/Index.html','utf8');
new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1].replace('<?!= initialData ?>','{}'));
const db={Quotations:[],Invoices:[],AuditLog:[]};let serial=0,locks=0;
const server={LockService:{getScriptLock:()=>({waitLock(){locks++},releaseLock(){locks--}})}};vm.createContext(server);vm.runInContext(code,server);
Object.assign(server,{require_(){},db_:()=>db,readSheet_:(_,name)=>db[name],id_:()=>`ID${++serial}`,audit_(){},append_(name,values){db[name].push(Object.fromEntries(vm.runInContext('APP.sheets.'+name,server).map((h,i)=>[h,values[i]])))}});
const defaults=server.solarTemplateDefaults_(),spec=server.solarPriceCatalog_().find(x=>x.kw===16&&x.type==='Hybrid On/Off-grid');
const source={id:'QT1',quoteNo:'QT8013092569',issueDate:'2026-09-13',workType:'Solar Cell',customerName:'บริษัท ทดสอบ <ลูกค้า>',customerAddress:'87 หมู่ที่ 1 จังหวัดขอนแก่น 40120',customerPhone:'095-238-3016',customerTaxId:'0403566004363',itemsJson:JSON.stringify([server.solarPackageItem_(spec)]),companyJson:JSON.stringify(server.solarCompanyDefaults_()),...defaults,subtotal:spec.price,vatRate:7,vatAmount:server.round_(spec.price*.07),grandTotal:server.round_(spec.price*1.07)};
db.Quotations.push(source);const user={id:'USER'},request={quotationId:'QT1',installment:1,issueDate:'2026-09-13',poNo:'PO-001'};
const first=server.createInvoice_(user,request);assert.equal(first.invoices.length,1);assert.equal(first.invoices[0].invoiceNo,'IV8013092569-1');assert.equal(first.invoices[0].grandTotal,source.grandTotal/2);
assert.equal(server.createInvoice_(user,request).issuedInvoiceId,first.issuedInvoiceId);assert.equal(db.Invoices.length,1);
const originalTotal=source.grandTotal,originalName=source.customerName;source.grandTotal=1;source.customerName='Changed customer';source.quoteNo='CHANGED';db.Quotations=[];
const result=server.createInvoice_(user,{...request,installment:2,issueDate:'2026-10-03'}),invoices=result.invoices;assert.equal(invoices.length,2);
assert.equal(invoices.reduce((s,x)=>s+x.grandTotal,0),originalTotal);assert(invoices.every(x=>x.quoteNo==='QT8013092569'&&x.snapshot.customerName===originalName));assert(invoices.find(x=>x.installment===2).invoiceNo==='IV8003102569-2');
assert.throws(()=>server.createInvoice_(user,{...request,installment:3}));assert.throws(()=>server.createInvoice_(user,{...request,issueDate:'2026-02-30'}));assert.throws(()=>server.createInvoice_(user,{...request,quotationId:'missing'}));assert.equal(locks,0);
server.require_=()=>{throw Error('Permission denied')};assert.throws(()=>server.createInvoice_(user,request),/Permission denied/);
for(let cents=1;cents<10000;cents+=17){const vat=Math.round(cents*.07),q={subtotal:cents/100,vatAmount:vat/100,grandTotal:(cents+vat)/100},a=server.invoiceAmounts_(q,1),b=server.invoiceAmounts_(q,2);for(const key of ['subtotal','vatAmount','grandTotal'])assert.equal(Math.round((a[key]+b[key])*100),Math.round(q[key]*100));assert(Math.abs(a.grandTotal-b.grandTotal)<.011);}
assert.throws(()=>server.invoiceAmounts_({subtotal:10,vatAmount:1,grandTotal:20},1));
let printed='',modal='';const page={};const client={S:{data:{quotations:[],invoices}},esc:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),money:n=>Number(n).toFixed(2),today:()=> '2026-09-13',displayDate:s=>s,modal:(title,body)=>modal=body,$:()=>page,window:{open:()=>({document:{write:s=>printed=s,close(){}},addEventListener(){},focus(){}})}};
vm.createContext(client);const names=['quotationSolarStamp','quotationCompany','quotationHeader','quotationSignatures','quotationCompanyAddress','quotationWarrantyText','quotationProjectTitle','quotationPackageRows','quotationDocumentRows','quotationDescriptionHtml','quotationColumns','quotationLineAmount','quotationPriceLabel','quotationTotals','quotationNote','quotationTerms','thaiDocumentDate','thaiIntegerText','thaiBahtText','nl2br','fitQuotationPrint','printQuotation','invoicePrintData','printInvoice','openInvoice','renderInvoices'];
vm.runInContext(html.split(/\r?\n/).filter(l=>names.some(n=>l.startsWith('function '+n+'('))).join('\n'),client);
for(const inv of invoices){client.printInvoice(inv.id);assert(printed.includes('Invoice / Tax Invoice'));const customerBlock=printed.split('class="quotation-customer-block"')[1].split('</header>')[0];assert(customerBlock.indexOf(inv.invoiceNo)<customerBlock.indexOf(inv.quoteNo));assert(customerBlock.indexOf(inv.quoteNo)<customerBlock.indexOf(client.thaiDocumentDate(inv.issueDate)));assert(customerBlock.indexOf(client.thaiDocumentDate(inv.issueDate))<customerBlock.indexOf('&lt;'));assert(printed.includes(inv.invoiceNo));assert(printed.includes(inv.quoteNo));assert(printed.includes(inv.paymentTerms));assert(printed.includes('ระยะดำเนินการตามตกลงของหน้างานและสัญญาโครงการ'));assert(printed.includes('ลูกค้า / ผู้รับเอกสาร'));assert(!printed.includes('ผู้อนุมัติใบเสนอราคา'));assert(printed.includes('&lt;ลูกค้า>'));assert(printed.includes(Number(inv.grandTotal).toFixed(2)));fs.writeFileSync('tests/invoice-paper-'+inv.installment+'.html',printed);}
client.openInvoice('QT1');assert(modal.includes('IV8013092569-1'));assert(modal.includes('IV8003102569-2'));assert(!modal.includes('onsubmit='));client.renderInvoices();assert(page.innerHTML.includes('QT8013092569'));
client.S.data.invoices=[invoices.find(x=>x.installment===1)];client.openInvoice('QT1');assert.equal((modal.match(/onsubmit=/g)||[]).length,1);assert(modal.includes('name="installment" value="2"'));
client.S.data.invoices=[];client.S.data.quotations=[invoices[0].snapshot];client.openInvoice('QT1');assert.equal((modal.match(/onsubmit=/g)||[]).length,2);
console.log('PASS: separate installment issuance, dates/numbers, repeat protection, permission, frozen QT/customer/totals, rounding reconciliation, invoice PDFs and saved-document UI');
