const fs=require('fs'),vm=require('vm'),http=require('http'),path=require('path'),{spawn}=require('child_process');
const h=fs.readFileSync('src/Index.html','utf8'),backend={};vm.createContext(backend);vm.runInContext(fs.readFileSync('src/Code.js','utf8'),backend);
let printHtml='',previewHtml='';
const quote={id:'TEST',quoteNo:'QTEV-202609-001',issueDate:'2026-09-12',customerName:'Example Customer Company',customerAddress:'Example address',customerPhone:'0123456789',customerTaxId:'1234567890123',items:backend.evPackageItems_(240,4,6990000),subtotal:6990000,vatRate:7,vatAmount:489300,grandTotal:7479300};
const ctx={S:{data:{quotations:[quote]}},esc:s=>String(s??'').replace(/</g,'&lt;'),money:n=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(n),thaiDocumentDate:s=>s,thaiBahtText:()=> 'เจ็ดล้านสี่แสนเจ็ดหมื่นเก้าพันสามร้อยบาทถ้วน',window:{open:()=>({document:{write:s=>printHtml=s,close(){}},addEventListener(){},focus(){}})}};
vm.createContext(ctx);const names=['quotationSolarStamp','quotationWarrantyText','quotationDocumentRows','quotationPackageRows','quotationDescriptionHtml','quotationCompanyAddress','quotationSignatureUpload','quotationProjectTitle','quotationCompany','quotationCompanyForm','quotationCompanyFromForm','fitQuotationPrint','quotationColumns','quotationLineAmount','quotationPriceLabel','quotationHeader','quotationTerms','quotationSignatures','quotationTotals','quotationNote','nl2br','printQuotation','renderQuotationPreview'];
vm.runInContext(h.split(/\r?\n/).filter(l=>names.some(n=>l.startsWith('function '+n+'('))) .join('\n'),ctx);
vm.runInContext(h.split(/\r?\n/).find(l=>l.startsWith('const QUOTE_DEFAULTS=')),ctx);
quote.warrantyText=vm.runInContext('QUOTE_DEFAULTS.warranty',ctx);quote.scopeText=vm.runInContext('QUOTE_DEFAULTS.scope',ctx);quote.paymentTerms='ชำระเงินภายใน 7 วัน นับจากวันที่ออกใบเสนอราคา';quote.deliveryTerms='ส่งมอบภายใน 4 เดือนหลังยืนยันใบสั่งซื้อ';
ctx.printQuotation('TEST');
if(process.env.QUOTE_TEST_SOLAR){const spec=backend.solarPriceCatalog_().find(x=>x.type==='Hybrid On/Off-grid'&&x.kw===16);Object.assign(quote,backend.solarTemplateDefaults_(),{workType:'Solar Cell',items:[backend.solarPackageItem_(spec)],subtotal:spec.price,vatAmount:spec.price*.07,grandTotal:spec.price*1.07});ctx.printQuotation('TEST');}
if(process.env.QUOTE_TEST_LOGO){quote.logoData='data:image/svg+xml;base64,'+Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="240" height="120"><rect width="240" height="120" fill="#f4c400"/><text x="120" y="72" text-anchor="middle" font-size="36">TEST LOGO</text></svg>').toString('base64');ctx.printQuotation('TEST');}
require('assert').ok(printHtml.includes('@page{size:A4;margin:12mm 10mm}'),'Equal 12 mm top/bottom print margins');
require('assert').ok(printHtml.includes('min-height:273mm'),'Printable A4 height accounts for both margins');
const out={};ctx.$=()=>out;ctx.quotationRowData=x=>x;ctx.document={querySelector:()=>({elements:Object.fromEntries(Object.entries(quote).map(([k,v])=>[k,{value:v}])),querySelectorAll:()=>quote.items})};ctx.renderQuotationPreview();previewHtml=out.innerHTML;
const styles=(h.replace(/<script>[\s\S]*?<\/script>/g,'').match(/<style[^>]*>[\s\S]*?<\/style>/g)||[]).join('');
const metrics=`<script>${ctx.fitQuotationPrint.toString()}addEventListener('load',()=>{fitQuotationPrint(window);const table=document.querySelector('.quote-document-table'),sheet=document.querySelector('.sheet,.quote-preview-sheet'),r=sheet.getBoundingClientRect();const cells=[...table.querySelectorAll('th,td')];document.title=JSON.stringify({width:r.width,height:r.height,companyNameWrapped:(()=>{const el=document.querySelector('.quotation-company-name');return el.getBoundingClientRect().height>parseFloat(getComputedStyle(el).lineHeight)+1})(),headerOverflow:[...document.querySelectorAll(".quotation-company-block,.quotation-brand-heading,.quotation-customer-block")].some(el=>el.scrollWidth>el.clientWidth+1),overflow:table.getBoundingClientRect().right>r.right+1,badCells:cells.filter(x=>x.scrollWidth>x.clientWidth+1).length,rows:table.tBodies[0].rows.length});});</script>`;
const server=http.createServer((req,res)=>res.end(req.url==='/print'?printHtml.replace('</body>',metrics+'</body>'):'<!doctype html><html><head><meta charset="utf-8">'+styles+'</head><body><div style="width:340px">'+previewHtml+'</div>'+metrics+'</body></html>'));
server.listen(0,'127.0.0.1',async()=>{try{for(const mode of ['print','preview']){const args=['--headless=new','--disable-gpu','--no-first-run','--user-data-dir='+path.resolve('tests/.edge-layout-profile'),'--window-size=1000,1200','--virtual-time-budget=3000','--screenshot='+path.resolve('tests/layout-paper-'+mode+'.png'),'--dump-dom','http://127.0.0.1:'+server.address().port+'/'+mode];const child=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args,{windowsHide:true});let output='';child.stdout.on('data',x=>output+=x);child.stderr.resume();await new Promise((resolve,reject)=>{child.on('close',resolve);child.on('error',reject)});const titles=[...output.matchAll(/<title>(.*?)<\/title>/g)],result=titles.at(-1)?.[1];console.log(mode,result);const m=JSON.parse(result);if((mode==='print'&&process.env.QUOTE_TEST_SOLAR&&m.companyNameWrapped)||m.headerOverflow||m.overflow||m.badCells||m.rows!==(process.env.QUOTE_TEST_SOLAR?12:8)||(mode==='print'&&m.height>1033))process.exitCode=1;}}finally{server.close()}});
