const fs=require('fs'),http=require('http'),path=require('path'),{spawn}=require('child_process'),assert=require('assert/strict');
const fixture=fs.readFileSync('tests/startup-performance.cjs','utf8'),data=new Function('require',fixture.slice(0,fixture.indexOf("console.log('PASS bootstrap"))+'return {startup,full};')(require);
const initial=JSON.stringify(data.full).replace(/</g,'\\u003c'),full=JSON.stringify(data.full).replace(/</g,'\\u003c');
const mock='<script>window.bootCalls=0;window.google={script:{get run(){const request={};return {withSuccessHandler(fn){request.success=fn;return this},withFailureHandler(fn){request.failure=fn;return this},api(action){window.bootCalls++;setTimeout(()=>request.success('+full+'),20)}}}}};</script>';
const page=fs.readFileSync('src/Index.html','utf8').replace('<?!= initialData ?>',initial).replace('<script>',mock+'<script>');
const exercise="<script>addEventListener('load',async()=>{await document.fonts.ready;const pages=['projects','finance','documents','loan','settings'];if(document.querySelector('#page-dashboard').children.length===0)throw Error('Dashboard missing');for(const p of pages)if(document.getElementById('page-'+p).innerHTML)throw Error('Hidden page rendered at startup: '+p);for(const p of pages){await showPage(p);const el=document.getElementById('page-'+p);if(!el.innerHTML||el.textContent.includes('แสดงผลไม่สำเร็จ'))throw Error('Page failed: '+p);}if(window.bootCalls!==0)throw Error('Duplicate bootstrap');await showPage('dashboard');document.title=JSON.stringify({passed:true,bootCalls:window.bootCalls,version:S.data.appVersion});});addEventListener('error',e=>document.title=JSON.stringify({error:e.message}));addEventListener('unhandledrejection',e=>document.title=JSON.stringify({error:String(e.reason)}));</script>";
const server=http.createServer((req,res)=>res.end(page.slice(0,page.lastIndexOf('</body>'))+exercise+'</body></html>'));
server.listen(0,'127.0.0.1',async()=>{let child,ws;try{
 const endpoint=await new Promise((resolve,reject)=>{child=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=0','--user-data-dir='+path.resolve('tests/.edge-layout-profile')],{windowsHide:true});let log='';child.stderr.on('data',x=>{log+=x;const match=log.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(match)resolve(match[1])});child.on('error',reject);child.on('exit',()=>reject(Error('Browser exited before debugger ready')))});
 const origin=endpoint.replace('ws:','http:').split('/devtools/')[0],target=await (await fetch(origin+'/json/new?about:blank',{method:'PUT'})).json();ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject});let id=0;const pending=new Map(),events=new Map();ws.onmessage=event=>{const msg=JSON.parse(event.data);if(msg.id){const p=pending.get(msg.id);pending.delete(msg.id);msg.error?p.reject(Error(JSON.stringify(msg.error))):p.resolve(msg.result)}else if(events.has(msg.method)){events.get(msg.method)();events.delete(msg.method)}};const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});await send('Page.enable');
 for(const width of [390,1280])for(const mode of ['startup']){await send('Emulation.setDeviceMetricsOverride',{width,height:1200,deviceScaleFactor:1,mobile:width<500});const loaded=new Promise(resolve=>events.set('Page.loadEventFired',resolve));await send('Page.navigate',{url:'http://127.0.0.1:'+server.address().port+'/'+mode});await loaded;const measured=await send('Runtime.evaluate',{expression:"(async()=>{for(let i=0;i<900;i++){if(document.title.startsWith('{'))return JSON.parse(document.title);await new Promise(r=>setTimeout(r,100))}throw Error('Timed out: '+window.pdfError)})()",awaitPromise:true,returnByValue:true});if(measured.exceptionDetails)throw Error(JSON.stringify(measured.exceptionDetails));const result=measured.result.value;console.log(width,mode,result);const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync('tests/document-archive-'+mode+'-'+width+'.png',Buffer.from(shot.data,'base64'));assert(!result.error,result.error);assert.equal(result.passed,true);assert.equal(result.bootCalls,0);}
 }catch(e){console.error(e);process.exitCode=1}finally{if(ws)ws.close();if(child)child.kill();server.close()}});
